# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 10:54
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(default='', verbose_name='\u6b63\u6587'),
        ),
    ]
